---
abstract: 'permute and expand glob-like text patterns'
author:
  - 'Nick Stokoe <wulee@cpan.org>'
build_requires:
  Module::Build: 0.28
configure_requires:
  Module::Build: 0.28
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
keywords:
  - text
  - glob
  - pattern
  - expand
  - braces
  - hostnames
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Glob-Expand
provides:
  Text::Glob::Expand:
    file: lib/Text/Glob/Expand.pm
    version: v1.1.1
  Text::Glob::Expand::Permutation:
    file: lib/Text/Glob/Expand/Permutation.pm
    version: 0
  Text::Glob::Expand::Segment:
    file: lib/Text/Glob/Expand/Segment.pm
    version: 0
requires:
  Sub::Exporter: 0
  Test::More: 0
  version: 0.77
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: https://github.com/wu-lee/Text-Glob-Expand
version: v1.1.1
